"""
Lightweight OTLP/HTTP trace exporter.

Reads Grafana settings from the DB and exports spans as OTLP JSON.
No dependency on the OpenTelemetry SDK — we build the payload manually
from the trace/span IDs already generated by the proxy router.
"""
from __future__ import annotations

import logging
import time
from typing import Any

import httpx

logger = logging.getLogger(__name__)

# In-memory settings cache (refreshed on each export call if stale)
_settings_cache: dict[str, str] | None = None
_settings_ts: float = 0.0
_CACHE_TTL = 30.0  # seconds


async def _load_settings() -> dict[str, str]:
    """Load grafana settings from DB, with a short TTL cache."""
    global _settings_cache, _settings_ts

    now = time.monotonic()
    if _settings_cache is not None and (now - _settings_ts) < _CACHE_TTL:
        return _settings_cache

    from sqlalchemy import select
    from aiguard.db.engine import async_session_factory
    from aiguard.db.models.setting import Setting

    try:
        async with async_session_factory() as session:
            result = await session.execute(select(Setting))
            rows = result.scalars().all()
        settings = {row.key: row.value for row in rows}
    except Exception:
        settings = {}

    _settings_cache = settings
    _settings_ts = now
    return settings


def _build_otlp_payload(
    *,
    service_name: str,
    trace_id: str,
    span_id: str,
    parent_span_id: str | None,
    span_name: str,
    start_time_ns: int,
    end_time_ns: int,
    status_code: int,
    attributes: list[dict[str, Any]],
    events: list[dict[str, Any]] | None = None,
) -> dict:
    """Build an OTLP ExportTraceServiceRequest JSON payload."""
    # OTLP status: 0 = UNSET, 1 = OK, 2 = ERROR
    otlp_status = 1 if status_code < 400 else 2

    span = {
        "traceId": trace_id,
        "spanId": span_id,
        "name": span_name,
        "kind": 2 if not parent_span_id else 3,  # SERVER for root, CLIENT for child
        "startTimeUnixNano": str(start_time_ns),
        "endTimeUnixNano": str(end_time_ns),
        "attributes": attributes,
        "status": {"code": otlp_status},
    }
    if parent_span_id:
        span["parentSpanId"] = parent_span_id
    if events:
        span["events"] = events

    return {
        "resourceSpans": [
            {
                "resource": {
                    "attributes": [
                        {"key": "service.name", "value": {"stringValue": service_name}},
                    ]
                },
                "scopeSpans": [
                    {
                        "scope": {"name": "aiguard", "version": "0.1.0"},
                        "spans": [span],
                    }
                ],
            }
        ]
    }


def _attr(key: str, value: Any) -> dict:
    """Build an OTLP attribute entry."""
    if isinstance(value, bool):
        return {"key": key, "value": {"boolValue": value}}
    if isinstance(value, int):
        return {"key": key, "value": {"intValue": str(value)}}
    if isinstance(value, float):
        return {"key": key, "value": {"doubleValue": value}}
    return {"key": key, "value": {"stringValue": str(value)}}


async def export_trace(
    *,
    trace_id: str,
    span_id: str,
    parent_span_id: str | None = None,
    request_id: str,
    provider: str,
    model: str,
    endpoint: str,
    scan_outcome: str,
    http_status: int,
    proxy_latency_ms: int,
    upstream_latency_ms: int | None = None,
    input_tokens: int | None = None,
    output_tokens: int | None = None,
    shields_triggered: list[str] | None = None,
    message_preview: str | None = None,
    request_body: dict | None = None,
    response_body: dict | None = None,
) -> None:
    """Export a single span to the configured OTLP endpoint (best-effort)."""
    settings = await _load_settings()

    if settings.get("grafana_enabled") != "true":
        return
    otlp_endpoint = settings.get("grafana_otlp_endpoint", "").rstrip("/")
    auth_header = settings.get("grafana_otlp_headers", "")
    service_name = settings.get("grafana_service_name", "") or "aiguard"

    if not otlp_endpoint:
        return

    # Build timing (use current time as end, subtract latency for start)
    end_ns = time.time_ns()
    start_ns = end_ns - (proxy_latency_ms * 1_000_000)

    # Build attributes
    attrs = [
        _attr("http.method", "POST"),
        _attr("http.status_code", http_status),
        _attr("http.url", endpoint),
        _attr("llm.provider", provider),
        _attr("llm.model", model),
        _attr("llm.scan_outcome", scan_outcome),
        _attr("llm.request_id", request_id),
        _attr("llm.proxy_latency_ms", proxy_latency_ms),
    ]
    if upstream_latency_ms is not None:
        attrs.append(_attr("llm.upstream_latency_ms", upstream_latency_ms))
    if input_tokens is not None:
        attrs.append(_attr("llm.input_tokens", input_tokens))
    if output_tokens is not None:
        attrs.append(_attr("llm.output_tokens", output_tokens))
    if shields_triggered:
        attrs.append(_attr("llm.shields_triggered", ",".join(shields_triggered)))
    if message_preview:
        attrs.append(_attr("llm.message", message_preview))

    # Build span events for request/response content
    import json as _json
    events: list[dict[str, Any]] = []
    if request_body:
        # Extract user messages for a readable summary
        messages = request_body.get("messages", [])
        user_msgs = [m.get("content", "") for m in messages if isinstance(m, dict) and m.get("role") == "user"]
        req_summary = user_msgs[-1][:2000] if user_msgs else _json.dumps(request_body)[:2000]
        events.append({
            "name": "llm.request",
            "timeUnixNano": str(start_ns),
            "attributes": [
                _attr("llm.request.model", request_body.get("model", model)),
                _attr("llm.request.message", req_summary),
                _attr("llm.request.body", _json.dumps(request_body)[:4000]),
            ],
        })
    if response_body:
        # Extract assistant response
        choices = response_body.get("choices", [])
        if choices and isinstance(choices[0], dict):
            msg = choices[0].get("message", {})
            resp_text = msg.get("content", "") if isinstance(msg, dict) else ""
        else:
            # Anthropic format
            content = response_body.get("content", [])
            resp_text = content[0].get("text", "") if content and isinstance(content[0], dict) else ""
        events.append({
            "name": "llm.response",
            "timeUnixNano": str(end_ns),
            "attributes": [
                _attr("llm.response.text", resp_text[:2000] if resp_text else ""),
                _attr("llm.response.body", _json.dumps(response_body)[:4000]),
            ],
        })

    payload = _build_otlp_payload(
        service_name=service_name,
        trace_id=trace_id,
        span_id=span_id,
        parent_span_id=parent_span_id,
        span_name=f"{provider} {model} {endpoint}",
        start_time_ns=start_ns,
        end_time_ns=end_ns,
        status_code=http_status,
        attributes=attrs,
        events=events or None,
    )

    url = f"{otlp_endpoint}/v1/traces"
    headers = {"Content-Type": "application/json"}
    if auth_header:
        headers["Authorization"] = auth_header

    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            resp = await client.post(url, json=payload, headers=headers)
        if resp.status_code >= 400:
            logger.debug("OTLP export failed: HTTP %d — %s", resp.status_code, resp.text[:200])
    except Exception as exc:
        logger.debug("OTLP export error: %s", exc)
